apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: backend
build:
  artifacts:
    - image: heno77/auth-image
      context: ./packages/auth
      docker:
        dockerfile: ./deploy/Dockerfile
    - image: heno77/story-image
      context: ./packages/story
      docker:
        dockerfile: ./deploy/Dockerfile
  local: { push: false }

manifests:
  rawYaml:
    - ./packages/auth/deploy/deployment.yaml
    - ./packages/story/deploy/deployment.yaml
    - ./infra/ingress.yaml
    - ./infra/rabbitmq.yaml
    # - ./infra/postgres.yaml
