apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-container
          image: heno77/auth-image
          ports:
            - containerPort: 7777
            - containerPort: 9999

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - name: http
      port: 8888
      targetPort: 7777
    - name: rpc
      port: 9999
      targetPort: 9999
  type: ClusterIP
