/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TopicsIndexImport } from './routes/topics/index'
import { Route as StoriesIndexImport } from './routes/stories/index'
import { Route as StoriesStoryIdImport } from './routes/stories/$storyId'
import { Route as TopicsTopicIdStoriesImport } from './routes/topics/$topicId.stories'
import { Route as TopicsTopicIdStoriesStoryIdImport } from './routes/topics/$topicId_.stories.$storyId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TopicsIndexRoute = TopicsIndexImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRoute,
} as any)

const StoriesIndexRoute = StoriesIndexImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRoute,
} as any)

const StoriesStoryIdRoute = StoriesStoryIdImport.update({
  id: '/stories/$storyId',
  path: '/stories/$storyId',
  getParentRoute: () => rootRoute,
} as any)

const TopicsTopicIdStoriesRoute = TopicsTopicIdStoriesImport.update({
  id: '/topics/$topicId/stories',
  path: '/topics/$topicId/stories',
  getParentRoute: () => rootRoute,
} as any)

const TopicsTopicIdStoriesStoryIdRoute =
  TopicsTopicIdStoriesStoryIdImport.update({
    id: '/topics/$topicId_/stories/$storyId',
    path: '/topics/$topicId/stories/$storyId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/stories/$storyId': {
      id: '/stories/$storyId'
      path: '/stories/$storyId'
      fullPath: '/stories/$storyId'
      preLoaderRoute: typeof StoriesStoryIdImport
      parentRoute: typeof rootRoute
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesIndexImport
      parentRoute: typeof rootRoute
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsIndexImport
      parentRoute: typeof rootRoute
    }
    '/topics/$topicId/stories': {
      id: '/topics/$topicId/stories'
      path: '/topics/$topicId/stories'
      fullPath: '/topics/$topicId/stories'
      preLoaderRoute: typeof TopicsTopicIdStoriesImport
      parentRoute: typeof rootRoute
    }
    '/topics/$topicId_/stories/$storyId': {
      id: '/topics/$topicId_/stories/$storyId'
      path: '/topics/$topicId/stories/$storyId'
      fullPath: '/topics/$topicId/stories/$storyId'
      preLoaderRoute: typeof TopicsTopicIdStoriesStoryIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/stories': typeof StoriesIndexRoute
  '/topics': typeof TopicsIndexRoute
  '/topics/$topicId/stories': typeof TopicsTopicIdStoriesRoute
  '/topics/$topicId/stories/$storyId': typeof TopicsTopicIdStoriesStoryIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/stories': typeof StoriesIndexRoute
  '/topics': typeof TopicsIndexRoute
  '/topics/$topicId/stories': typeof TopicsTopicIdStoriesRoute
  '/topics/$topicId/stories/$storyId': typeof TopicsTopicIdStoriesStoryIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/stories/': typeof StoriesIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/topics/$topicId/stories': typeof TopicsTopicIdStoriesRoute
  '/topics/$topicId_/stories/$storyId': typeof TopicsTopicIdStoriesStoryIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/stories/$storyId'
    | '/stories'
    | '/topics'
    | '/topics/$topicId/stories'
    | '/topics/$topicId/stories/$storyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/stories/$storyId'
    | '/stories'
    | '/topics'
    | '/topics/$topicId/stories'
    | '/topics/$topicId/stories/$storyId'
  id:
    | '__root__'
    | '/'
    | '/stories/$storyId'
    | '/stories/'
    | '/topics/'
    | '/topics/$topicId/stories'
    | '/topics/$topicId_/stories/$storyId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StoriesStoryIdRoute: typeof StoriesStoryIdRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
  TopicsTopicIdStoriesRoute: typeof TopicsTopicIdStoriesRoute
  TopicsTopicIdStoriesStoryIdRoute: typeof TopicsTopicIdStoriesStoryIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StoriesStoryIdRoute: StoriesStoryIdRoute,
  StoriesIndexRoute: StoriesIndexRoute,
  TopicsIndexRoute: TopicsIndexRoute,
  TopicsTopicIdStoriesRoute: TopicsTopicIdStoriesRoute,
  TopicsTopicIdStoriesStoryIdRoute: TopicsTopicIdStoriesStoryIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/stories/$storyId",
        "/stories/",
        "/topics/",
        "/topics/$topicId/stories",
        "/topics/$topicId_/stories/$storyId"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/stories/$storyId": {
      "filePath": "stories/$storyId.jsx"
    },
    "/stories/": {
      "filePath": "stories/index.jsx"
    },
    "/topics/": {
      "filePath": "topics/index.jsx"
    },
    "/topics/$topicId/stories": {
      "filePath": "topics/$topicId.stories.jsx"
    },
    "/topics/$topicId_/stories/$storyId": {
      "filePath": "topics/$topicId_.stories.$storyId.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
