/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as StoriesIndexImport } from './routes/stories/index'
import { Route as StoriesStoryIdImport } from './routes/stories/$storyId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StoriesIndexRoute = StoriesIndexImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRoute,
} as any)

const StoriesStoryIdRoute = StoriesStoryIdImport.update({
  id: '/stories/$storyId',
  path: '/stories/$storyId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/stories/$storyId': {
      id: '/stories/$storyId'
      path: '/stories/$storyId'
      fullPath: '/stories/$storyId'
      preLoaderRoute: typeof StoriesStoryIdImport
      parentRoute: typeof rootRoute
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/stories': typeof StoriesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/stories': typeof StoriesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/stories/$storyId': typeof StoriesStoryIdRoute
  '/stories/': typeof StoriesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/stories/$storyId' | '/stories'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/stories/$storyId' | '/stories'
  id: '__root__' | '/' | '/stories/$storyId' | '/stories/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StoriesStoryIdRoute: typeof StoriesStoryIdRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StoriesStoryIdRoute: StoriesStoryIdRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/stories/$storyId",
        "/stories/"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/stories/$storyId": {
      "filePath": "stories/$storyId.jsx"
    },
    "/stories/": {
      "filePath": "stories/index.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
